<?php

header('Content-Type: text/html; charset=UTF-8');

echo '<!DOCTYPE html>'
    .'<html>'
        .'<head>'
            .'<title></title>'
            .'<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />'
            .'<meta name="viewport" content="width=device-width, user-scalable=no" />'
            .'<link rel="stylesheet" type="text/css" href="js/Main.css" />'
            .'<link rel="stylesheet" type="text/css" href="css/Button.css" />'
            .'<link rel="stylesheet" type="text/css" href="js/Canvas.css" />'
            .'<link rel="stylesheet" type="text/css" href="js/ColorButtonsPanel.css" />'
            .'<link rel="stylesheet" type="text/css" href="js/EditColorPanel.css" />'
            .'<link rel="stylesheet" type="text/css" href="js/FileButton.css" />'
            .'<link rel="stylesheet" type="text/css" href="js/FilePanel.css" />'
            .'<link rel="stylesheet" type="text/css" href="js/MainPanel.css" />'
            .'<link rel="stylesheet" type="text/css" href="js/PalettePanel.css" />'
            .'<link rel="stylesheet" type="text/css" href="js/Slider.css" />'
            .'<link rel="stylesheet" type="text/css" href="js/ParamsPanel.css" />'
        .'</head>'
        .'<body>'
            .'<script type="text/javascript" src="js/BarButton.js"></script>'
            .'<script type="text/javascript" src="js/BrushTool.js"></script>'
            .'<script type="text/javascript" src="js/Canvas.js"></script>'
            .'<script type="text/javascript" src="js/ColorButton.js"></script>'
            .'<script type="text/javascript" src="js/ColorButtonsPanel.js"></script>'
            .'<script type="text/javascript" src="js/Div.js"></script>'
            .'<script type="text/javascript" src="js/EditColorPanel.js"></script>'
            .'<script type="text/javascript" src="js/EraserTool.js"></script>'
            .'<script type="text/javascript" src="js/FileButton.js"></script>'
            .'<script type="text/javascript" src="js/FilePanel.js"></script>'
            .'<script type="text/javascript" src="js/MainPanel.js"></script>'
            .'<script type="text/javascript" src="js/PalettePanel.js"></script>'
            .'<script type="text/javascript" src="js/ParamsPanel.js"></script>'
            .'<script type="text/javascript" src="js/SaveCanvas.js"></script>'
            .'<script type="text/javascript" src="js/Slider.js"></script>'
            .'<script type="text/javascript" src="js/Main.js"></script>'
        .'</body>'
    .'</html>';
